#include <gtest/gtest.h>

#include "input/controller.hpp"

using button = cen::controller_button;

TEST(ControllerButton, EqualityOperator)
{
  ASSERT_EQ(button::invalid, SDL_CONTROLLER_BUTTON_INVALID);
  ASSERT_EQ(button::a, SDL_CONTROLLER_BUTTON_A);
  ASSERT_EQ(button::b, SDL_CONTROLLER_BUTTON_B);
  ASSERT_EQ(button::x, SDL_CONTROLLER_BUTTON_X);
  ASSERT_EQ(button::y, SDL_CONTROLLER_BUTTON_Y);
  ASSERT_EQ(button::back, SDL_CONTROLLER_BUTTON_BACK);
  ASSERT_EQ(button::guide, SDL_CONTROLLER_BUTTON_GUIDE);
  ASSERT_EQ(button::start, SDL_CONTROLLER_BUTTON_START);
  ASSERT_EQ(button::left_stick, SDL_CONTROLLER_BUTTON_LEFTSTICK);
  ASSERT_EQ(button::right_stick, SDL_CONTROLLER_BUTTON_RIGHTSTICK);
  ASSERT_EQ(button::left_shoulder, SDL_CONTROLLER_BUTTON_LEFTSHOULDER);
  ASSERT_EQ(button::right_shoulder, SDL_CONTROLLER_BUTTON_RIGHTSHOULDER);
  ASSERT_EQ(button::dpad_up, SDL_CONTROLLER_BUTTON_DPAD_UP);
  ASSERT_EQ(button::dpad_down, SDL_CONTROLLER_BUTTON_DPAD_DOWN);
  ASSERT_EQ(button::dpad_left, SDL_CONTROLLER_BUTTON_DPAD_LEFT);
  ASSERT_EQ(button::dpad_right, SDL_CONTROLLER_BUTTON_DPAD_RIGHT);
  ASSERT_EQ(button::max, SDL_CONTROLLER_BUTTON_MAX);

  ASSERT_EQ(SDL_CONTROLLER_BUTTON_INVALID, button::invalid);
  ASSERT_EQ(SDL_CONTROLLER_BUTTON_A, button::a);
  ASSERT_EQ(SDL_CONTROLLER_BUTTON_B, button::b);
  ASSERT_EQ(SDL_CONTROLLER_BUTTON_X, button::x);
  ASSERT_EQ(SDL_CONTROLLER_BUTTON_Y, button::y);
  ASSERT_EQ(SDL_CONTROLLER_BUTTON_BACK, button::back);
  ASSERT_EQ(SDL_CONTROLLER_BUTTON_GUIDE, button::guide);
  ASSERT_EQ(SDL_CONTROLLER_BUTTON_START, button::start);
  ASSERT_EQ(SDL_CONTROLLER_BUTTON_LEFTSTICK, button::left_stick);
  ASSERT_EQ(SDL_CONTROLLER_BUTTON_RIGHTSTICK, button::right_stick);
  ASSERT_EQ(SDL_CONTROLLER_BUTTON_LEFTSHOULDER, button::left_shoulder);
  ASSERT_EQ(SDL_CONTROLLER_BUTTON_RIGHTSHOULDER, button::right_shoulder);
  ASSERT_EQ(SDL_CONTROLLER_BUTTON_DPAD_UP, button::dpad_up);
  ASSERT_EQ(SDL_CONTROLLER_BUTTON_DPAD_DOWN, button::dpad_down);
  ASSERT_EQ(SDL_CONTROLLER_BUTTON_DPAD_LEFT, button::dpad_left);
  ASSERT_EQ(SDL_CONTROLLER_BUTTON_DPAD_RIGHT, button::dpad_right);
  ASSERT_EQ(SDL_CONTROLLER_BUTTON_MAX, button::max);
}

TEST(ControllerButton, InequalityOperator)
{
  ASSERT_NE(button::dpad_right, SDL_CONTROLLER_BUTTON_LEFTSHOULDER);
  ASSERT_NE(SDL_CONTROLLER_BUTTON_X, button::a);

  ASSERT_FALSE(SDL_CONTROLLER_BUTTON_INVALID != button::invalid);
}
