/*
 * MIT License
 *
 * Copyright (c) 2019-2020 Albin Johansson
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#ifndef CENTURION_MOUSE_MOTION_EVENT_HEADER
#define CENTURION_MOUSE_MOTION_EVENT_HEADER

#include <SDL_events.h>

#include "centurion_api.h"
#include "common_event.h"
#include "mouse_button.h"

namespace centurion {
namespace event {

/**
 * The MouseMotionEvent class represents events that are triggered by the
 * movement of the mouse.
 *
 * @see SDL_MouseMotionEvent
 * @since 4.0.0
 */
class MouseMotionEvent : public CommonEvent<SDL_MouseMotionEvent> {
 public:
  /**
   * Creates a default-initialized MouseMotionEvent.
   *
   * @since 4.0.0
   */
  CENTURION_API MouseMotionEvent() noexcept;

  /**
   * Creates a MouseMotionEvent that is based on the supplied SDL event.
   *
   * @param event the SDL event that will be copied.
   * @since 4.0.0
   */
  CENTURION_API MouseMotionEvent(const SDL_MouseMotionEvent& event) noexcept;

  /**
   * Creates a MouseMotionEvent that is based on the supplied SDL event.
   *
   * @param event the SDL event that will be moved.
   * @since 4.0.0
   */
  CENTURION_API MouseMotionEvent(SDL_MouseMotionEvent&& event) noexcept;

  /**
   * Sets the window ID associated with the event.
   *
   * @param id the window ID associated with the event.
   * @since 4.0.0
   */
  CENTURION_API void set_window_id(Uint32 id) noexcept;

  /**
   * Sets the mouse instance ID, or SDL_TOUCH_MOUSEID depending on the type
   * of the event.
   *
   * @param which the mouse instance ID, or SDL_TOUCH_MOUSEID.
   * @since 4.0.0
   */
  CENTURION_API void set_which(Uint32 which) noexcept;

  /**
   * Sets the mouse button state associated with the event. The value could
   * be any of SDL_BUTTON_LMASK, SDL_BUTTON_MMASK, SDL_BUTTON_RMASK,
   * SDL_BUTTON_X1MASK and SDL_BUTTON_X2MASK OR'd together.
   *
   * @param state the mouse button state associated with the event.
   * @since 4.0.0
   */
  CENTURION_API void set_state(Uint32 state) noexcept;

  /**
   * Sets the x-coordinate of the mouse relative to the mouse that is
   * associated with the event.
   *
   * @param x the x-coordinate of the mouse.
   * @since 4.0.0
   */
  CENTURION_API void set_x(Sint32 x) noexcept;

  /**
   * Sets the y-coordinate of the mouse relative to the mouse that is
   * associated with the event.
   *
   * @param y the y-coordinate of the mouse.
   * @since 4.0.0
   */
  CENTURION_API void set_y(Sint32 y) noexcept;

  /**
   * Sets the value of the relative motion of the mouse along the x-axis.
   *
   * @param dx the value of the relative motion of the mouse along the x-axis.
   * @since 4.0.0
   */
  CENTURION_API void set_dx(Sint32 dx) noexcept;

  /**
   * Sets the value of the relative motion of the mouse along the y-axis.
   *
   * @param dy the value of the relative motion of the mouse along the y-axis.
   * @since 4.0.0
   */
  CENTURION_API void set_dy(Sint32 dy) noexcept;

  /**
   * Returns the window ID associated with the event.
   *
   * @return the window ID associated with the event.
   * @since 4.0.0
   */
  CENTURION_NODISCARD
  CENTURION_API Uint32 window_id() const noexcept;

  /**
   * Returns the mouse instance ID, or SDL_TOUCH_MOUSEID. The returned value
   * might be SDL_TOUCH_MOUSEID for events that were generated by a touch
   * input device.
   *
   * @return the mouse instance ID, or SDL_TOUCH_MOUSEID.
   * @since 4.0.0
   */
  CENTURION_NODISCARD
  CENTURION_API Uint32 which() const noexcept;

  /**
   * Returns a bitmask for the current mouse button state. If you want to
   * check if a specific mouse button is pressed or released, a better
   * alternative would be to use the <code>pressed(MouseButton)</code> method.
   *
   * @return  a bitmask for the current mouse button state.
   * @since 4.0.0
   */
  CENTURION_NODISCARD
  CENTURION_API Uint32 state() const noexcept;

  /**
   * Indicate whether or not a mouse button is pressed.
   *
   * @param button the mouse button that will be checked.
   * @return true if the specified mouse button is pressed; false otherwise.
   * @since 4.0.0
   */
  CENTURION_NODISCARD
  CENTURION_API bool pressed(MouseButton button) const noexcept;

  /**
   * Returns the x-coordinate of the mouse relative to the window.
   *
   * @return the x-coordinate of the mouse relative to the window.
   * @since 4.0.0
   */
  CENTURION_NODISCARD
  CENTURION_API Sint32 x() const noexcept;

  /**
   * Returns the y-coordinate of the mouse relative to the window.
   *
   * @return the y-coordinate of the mouse relative to the window.
   * @since 4.0.0
   */
  CENTURION_NODISCARD
  CENTURION_API Sint32 y() const noexcept;

  /**
   * Returns the relative motion of the mouse along the x-axis.
   *
   * @return the relative motion of the mouse along the x-axis.
   * @since 4.0.0
   */
  CENTURION_NODISCARD
  CENTURION_API Sint32 dx() const noexcept;

  /**
   * Returns the relative motion of the mouse along the y-axis.
   *
   * @return the relative motion of the mouse along the y-axis.
   * @since 4.0.0
   */
  CENTURION_NODISCARD
  CENTURION_API Sint32 dy() const noexcept;
};

static_assert(validate_event<MouseMotionEvent, SDL_MouseMotionEvent>(),
              "MouseMotionEvent failed the event type specification!");

}  // namespace event
}  // namespace centurion

#ifdef CENTURION_HEADER_ONLY
#include "mouse_motion_event.cpp"
#endif  // CENTURION_HEADER_ONLY

#endif  // CENTURION_MOUSE_MOTION_EVENT_HEADER