name: "CI"

on:
  - "push"

jobs:
  macos-build-and-test:
    runs-on: "macos-latest"
    steps:
      - uses: "actions/checkout@v4"
        with:
          submodules: "recursive"

      - name: "Select Xcode version"
        run: |
          sudo xcode-select --switch /Applications/Xcode_16.3.app

      - name: "Install system dependencies"
        run: |
          brew install cmake
          brew install ninja

      - name: "Generate build files"
        run: |
          mkdir build
          cd build
          cmake .. --preset=testing-dbg                \
                   --log-level=DEBUG                   \
                   -DCMAKE_COMPILE_WARNING_AS_ERROR=ON

      - name: "Build"
        run: |
          ninja -C build
