name: "CI: Ubuntu"

on: [ push ]

env:
  SDL_LATEST: 2.24.0
  SDL_VIDEODRIVER: x11
  DISPLAY: :99.0

jobs:
  ubuntu-test:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '[skip-ci]') == false
    strategy:
      matrix:
        SDL_VERSION: [ 2.0.18, 2.0.20, 2.0.22, 2.24.0 ]
        CPP_VERSION: [ 17, 20 ]
        include:
          - SDL_VERSION: 2.0.10
            CPP_VERSION: 17
          - SDL_VERSION: 2.0.12
            CPP_VERSION: 17
          - SDL_VERSION: 2.0.14
            CPP_VERSION: 17
          - SDL_VERSION: 2.0.16
            CPP_VERSION: 17
          - SDL_VERSION: 2.0.22
            CPP_VERSION: 23
    steps:
      - uses: actions/checkout@main
      - uses: seanmiddleditch/gha-setup-ninja@master
      - uses: lukka/get-cmake@latest

      - name: Update packages
        shell: bash
        run: sudo apt update

      - name: Install graphics drivers
        shell: bash
        run: sudo apt-get install libegl1-mesa-dev libgles2-mesa-dev libasound2-dev libpulse-dev

      - name: Install code coverage tools
        if: ${{ matrix.SDL_VERSION == env.SDL_LATEST && matrix.CPP_VERSION == '20' }}
        shell: bash
        run: |
          sudo apt-get install -y libjson-perl

          # Manually builds latest LCOV
          git clone https://github.com/linux-test-project/lcov.git lcov
          cd lcov
          sudo make install
          cd ..

      - name: Emulate video device
        shell: bash
        run: |
          sudo apt install xvfb
          /sbin/start-stop-daemon --start --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 800x600x24 -ac +extension GLX;
          sleep 3

      - name: Cache SDL2
        id: cache-sdl2
        uses: actions/cache@main
        with:
          path: SDL2-${{matrix.SDL_VERSION}}
          key: SDL2-${{matrix.SDL_VERSION}}

      - name: Build SDL2
        shell: bash
        if: steps.cache-sdl2.outputs.cache-hit != 'true'
        run: |
          curl -L https://www.libsdl.org/release/SDL2-${{matrix.SDL_VERSION}}.tar.gz | tar xz
          cd SDL2-${{matrix.SDL_VERSION}}
          ./configure
          make -j 8

      - name: Install SDL2
        shell: bash
        run: |
          cd SDL2-${{matrix.SDL_VERSION}}
          sudo make install

      - name: Install SDL2_image
        shell: bash
        run: sudo apt install libsdl2-image-dev

      - name: Install SDL2_mixer
        shell: bash
        run: sudo apt install libsdl2-mixer-dev

      - name: Install SDL2_ttf
        shell: bash
        run: sudo apt install libsdl2-ttf-dev

      - name: Create build directory
        shell: bash
        run: mkdir -p build

      - name: Generate build files
        working-directory: ./build
        shell: bash
        run: |
          if [[ "${{matrix.SDL_VERSION}}" == "${{env.SDL_LATEST}}" && "${{matrix.CPP_VERSION}}" == "20" ]];
          then
            cmake .. -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_STANDARD=${{matrix.CPP_VERSION}} -DCEN_TESTS=ON -DCEN_EXAMPLES=ON -DCEN_AUDIO=OFF -DCEN_COVERAGE=ON -GNinja
          else
            cmake .. -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_STANDARD=${{matrix.CPP_VERSION}} -DCEN_TESTS=ON -DCEN_AUDIO=OFF -GNinja
          fi

      - name: Build
        working-directory: ./build
        shell: bash
        run: ninja

      - name: Run mocked test suite
        working-directory: ./build/test/mocked-tests
        shell: bash
        run: ./mockcenturion

      - name: Run unit tests
        working-directory: ./build/test/unit-tests
        shell: bash
        run: ./testcenturion

      - name: Capture code coverage
        if: ${{matrix.SDL_VERSION == env.SDL_LATEST && matrix.CPP_VERSION == '20' }}
        working-directory: ./build
        shell: bash
        run: |
          lcov --directory . --capture --output-file coverage.info --gcov-tool gcov-9
          lcov --remove coverage.info '*/test/*' '*/lib/*' '/usr/*' --output-file coverage.info
          lcov --list coverage.info
          bash <(curl -s https://codecov.io/bash) -X gcov || echo "Codecov did not collect coverage reports"